export const WRITE_FIRSTNAME = 'WRITE_FIRSTNAME';
export const WRITE_LASTNAME = 'WRITE_LASTNAME';
export const WRITE_FIRST_EMAIL = 'WRITE_FIRST_EMAIL';
export const WRITE_SECOND_EMAIL = 'WRITE_SECOND_EMAIL';
export const WRITE_PASSWORD = 'WRITE_PASSWORD';
export const SET_LOGIN_REDIRECT = 'SET_LOGIN_REDIRECT';

